---
title: "Figure 2"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
suppressPackageStartupMessages(source("scripts/themes.R"))
tm.facs <- loadObject(filename = url("https://scfind.cog.sanger.ac.uk/indexes/tm_facs.rds"))
tm.10x <- loadObject(filename = url("https://scfind.cog.sanger.ac.uk/indexes/tm_10X.rds"))
```

## Table 2a
```{r paged.print=TRUE}
table.2a <- hyperQueryCellTypes(object = tm.facs, 
                    gene.list = c("Il2ra", "Ptprc", "Il7r", "Ctla4"))

table.2a[order(table.2a$pval, decreasing = F),]
```


## Figure 2b
```{r message=FALSE, warning=FALSE}
source("scripts/2b.R")

gating <- list("Naive T cells" = c("-Il2ra", "Ptprc", "Il7r"),
               "Effector T cells" = c("Il2ra", "-Il7r"),
               "Effector Memory T cells" = c("-*Il2ra", "-*Ptprc", "Il7r"),
               "Central Memory T cells" = c("Il2ra", "-Ptprc", "Il7r"),
               "Resting T Reg cells" = c("Il2ra", "Ptprc", "Il7r", "-Ctla4"))

celltype = c()
dataset = c()
number_of_cell = c()

total_tm10x <- tm.10x@index$getCellTypeMeta("Thymus.T cell")$total_cells
total_tmfacs <- tm.facs@index$getCellTypeMeta("Thymus.T cell")$total_cells

for( i in names(gating))
{
    celltype <- c(celltype, rep(i, 2))
    dataset <- c(dataset, paste0("TM, 10X\n(",total_tm10x," cells)\n") , paste0("TM, FACS\n(",total_tmfacs, " cells)\n") )
    number_of_cell <- c( number_of_cell, 
                         as.numeric(length(findCellTypes(tm.10x, gating[[i]], "Thymus")[["Thymus.T cell"]])),
                         as.numeric(length(findCellTypes(tm.facs, gating[[i]] , "Thymus")[["Thymus.T cell"]]))  )
}

df <- data.frame("celltype" = celltype, "Atlas" = dataset, "number_of_cell" = number_of_cell)
df$celltype <- stringr::str_wrap(df$celltype, width = 10)

p.2b <- ggplot(df, aes(x = celltype, y = number_of_cell, fill = Atlas)) + 
    main + 
    ylab("Number of cells") + 
    scale_fill_manual("Atlas", values = c("#7570B3", "#E7298A") )  + xlab("") + 
    geom_bar(stat="identity", position = position_dodge()) + 
    annotate("point", x = 1:5, y = -20, size = 3, colour =  cbPalette[1:5], alpha = .6)+ theme(axis.text.x = element_blank())

p2b.facs <- plot.gating(tm.facs, "Thymus.T cell", "Thymus", "pca", gating) + 
    theme(strip.background = element_blank(), strip.text.x = element_blank()) +
    scale_color_manual("T cell subtypes", values = cbPalette[1:5])

p2b.10x <- plot.gating(tm.10x, "Thymus.T cell", "Thymus", "pca", gating) + 
    theme(strip.background = element_blank(), strip.text.x = element_blank()) +
    scale_color_manual("T cell subtypes", values = cbPalette[1:5])
```

## Figure 2c
```{r}
gene.list.cellMarker <-  c("Acta1", "Actc1", "Atp2a2", "Myh6", "Nppa")

gene.list.scfind <- as.character(cellTypeMarkers(tm.facs, 
                                                 cell.types = "Heart.cardiac muscle cell", 
                                                 sort.field = "f1", 
                                                 background.cell.types = cellTypeNames(tm.facs, "Heart"))$genes
                                 )

eva.cellMarker <- evaluateMarkers(tm.facs, gene.list.cellMarker, cell.types = "Heart.cardiac muscle cell",  
                                  background.cell.types = cellTypeNames(tm.facs, "Heart"), 
                                  sort.field = "f1")
eva.cellMarker$`Marker Genes` <- "CellMarker"

eva.scfind <- evaluateMarkers(tm.facs, gene.list.scfind, cell.types = "Heart.cardiac muscle cell", 
                              background.cell.types = cellTypeNames(tm.facs, "Heart"), 
                              sort.field = "f1")
eva.scfind$`Marker Genes` <- "SCfind"

df.2c <- rbind(eva.cellMarker, eva.scfind)

p.2c <- ggplot(df.2c, aes(x = precision, y = recall, colour =  `Marker Genes`, shape = `Marker Genes`)) + 
    main + 
    xlab("Precision") + ylab("Recall") + xlim(0, 1) + ylim(0,1) +
    scale_colour_manual(values = tritPalette[2:3]) + scale_shape_manual(values = c(13,19)) + 
    geom_point(size = 5, alpha = 0.8)
```

## Figure 2d
```{r message=FALSE, warning=FALSE}
df.2d <- read.table("data/fig2d.csv", sep = ",", header = T, stringsAsFactors = F)

p.2d <- ggplot(df.2d, aes(x = as.character(no_of_genes), y = score, fill = type)) + 
    main + 
    xlab("Number of genes") + ylab("Score") + 
    scale_fill_manual("Score type", values = cbPalette) + 
    geom_boxplot(size = .2, notch = T, outlier.size = .2) + 
    facet_grid(. ~ query)
```

### Figure 2
```{r message=FALSE, warning=FALSE}
plot_grid(
    p.2b + theme(legend.position = "none"),
    plot_grid(get_legend(p.2b), get_legend(p2b.facs)),
    p2b.facs + theme(legend.position = "none"),
    p2b.10x + theme(legend.position = "none"),
    labels = c('B'),
    ncol = 2, nrow = 2
)

plot_grid(
    plot_grid(p.2c + theme(legend.position = "none"),
    plot_grid(get_legend(p.2c),
    get_legend(p.2d)), ncol = 2),
    p.2d + theme(legend.position = "none"),
    labels = c('C', 'D'),
    ncol = 1, nrow = 2
)
```

