---
title: "Figure 3"
output: html_notebook
---


```{r}
suppressPackageStartupMessages(source("scripts/themes.R"))
```

## Figure 3a
```{r message=FALSE, warning=FALSE}
df.3a <- read.table("data/fig3a.csv", sep = ",", header = T, stringsAsFactors = F)

p.3a <-  ggplot(df.3a, aes(x = values, fill = atlas)) + geom_density(alpha=.8, aes(y = ..scaled..)) + 
    main  + theme(panel.margin = unit(-3, "lines"),strip.text.y = element_blank() ) + scale_y_continuous(breaks = c(1)) +
    labs(x = "Number of cell types", y = "Gene/peak\ndensity (arbitrary)", fill = "Atlas") + 
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format("log10", math_format(10^.x))) + 
    scale_fill_manual(values = RColorBrewer::brewer.pal(8,colorcode)) + 
    facet_grid(atlas~.)
```


## Figure 3b
```{r message=FALSE, warning=FALSE}
df.3b <- readRDS("data/fig3b.rds")

p.3b <- upset(fromList((df.3b)), 
              order.by="freq", 
              empty.intersections = "off", 
              sets.bar.color = RColorBrewer::brewer.pal(8,colorcode)[c(4:2,8)], 
              sets = c("TM, FACS","TM, 10X","MCA", "Eisenberg & Levanon" ), 
              mainbar.y.label = "House Keeping Gene\nIntersection", 
              text.scale = c(2.5), mb.ratio = c(.7,.3), number.angles = -45, scale.sets = "log10", point.size = 5, line.size = 3)

p.3b
```

### Figure 3
```{r warning=FALSE}
plot_grid(
    p.3a + theme(legend.position="bottom") + guides(fill = guide_legend(title.position = "top")),
    NULL, 
    labels = c('A', 'B'),
    ncol = 2
)
```

