---
title: "Figure 7"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
suppressPackageStartupMessages(source("scripts/themes.R"))
```

### Figure 7
```{r message=FALSE, warning=FALSE}
df.7 <- readRDS("data/fig7a.rds")

chromosome_anno <- Heatmap(df.7$chromosome_anno, 
                           name = "Chromosome", 
                           col = df.7$chr_grp,
                           cluster_rows = F,
                           heatmap_legend_param = list(direction = "horizontal", nrow = 2),
                           width = unit(5, "mm"), show_heatmap_legend = T)

Distance_anno <- Heatmap(df.7$Distance_anno, 
                         name = "Distance from TSS (kb)", 
                         col = c("white", "black"),
                         cluster_rows = F, show_column_names = F,
                         heatmap_legend_param = list(at = df.7$bp.legend[2:length(df.7$bp.legend)] * 1000,
                                                     labels = signif(df.7$bp.legend[2:length(df.7$bp.legend)], 1),
                                                     direction = "horizontal"),width = unit(5, "mm"))

draw(
   chromosome_anno + Distance_anno + Heatmap(df.7$mx, 
                                             col = c("white", "#49006A"),
                                             name = "Cell hits", column_title = gsub(".*\\.", "", as.character(df.7$i)),
                                             cluster_rows = F, cluster_columns = F,
                                             show_row_names = F,
                                             heatmap_legend_param = list(direction = "horizontal"),
                                             column_names_gp = gpar(fontsize = 12)
                                             ),
   heatmap_legend_side = "top")
```


